esphome:
  name: hwc-monitor
  includes:
    - datos/uart_read_line_sensor.h

esp8266:
  board: nodemcuv2

# Enable logging
logger:
  level: VERBOSE #makes uart stream available in esphome logstream
  baud_rate: 0 #disable logging over uart


# Enable Home Assistant API
api:
  encryption:
    key: "OSvqW/yDWlIwdFtaHHFBimuXhic5jmF6lTQO5new+q4="

ota:
  password: "48715da5f021aad02d4f4ce78f9e1c86"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Hwc-Monitor Fallback Hotspot"
    password: "ADekUGzzM6Kf"

captive_portal:

uart:
  id: uart_bus
  tx_pin: GPIO1 
  rx_pin: GPIO3 
  baud_rate: 57600

text_sensor:
- platform: custom
  lambda: |-
    auto my_custom_sensor = new UartReadLineSensor(id(uart_bus));
    App.register_component(my_custom_sensor);
    return {my_custom_sensor};
  text_sensors:
    id: "uart_readline"    
    
switch:
  - platform: uart
    name: "Send_%"
    data: '%'
  
